chess/src/App.js, chess/src/Components/CreateAccount.js, chess/src/Components/Networking.js
Created CreateAccount component along with Networking component for functionality
=> Networking

chess/src/Components/Networking.js
=> added networking for login

chess/src/Components/GetCookies.js, chess/src/Components/LogIn.js
Retrieve cookie object from backend with key value pairs.
Contains sessionId, user_id and user.
=> Created cookie function

chess/src/App.js, chess/src/Components/Header.js, chess/src/Components/HomePage.js, chess/src/Components/home.css
Created header with logo placeholder, home button, logout button - logout functionality not yet added
=> made header component

chess/src/App.js, chess/src/Components/CreateAccount.js, chess/src/Components/Leaderboard.js, chess/src/Components/LogIn.js, chess/src/Components/Networking.js, chess/yarn.lock
Cookies are set when a user session begins.
Passed cookie props to components from App.js.
=> Setting cookies for when a user logs in

chess/src/App.js, chess/src/Components/CreateAccount.js, chess/src/Components/Header.js, chess/src/Components/Leaderboard.js, chess/src/Components/LogIn.js, chess/src/Components/Networking.js, chess/yarn.lock
Added log out to networking component.
Still have issues with retrieving correct user id and updating it.
=> Log out network

chess/src/Components/Header.js, chess/src/Components/LogIn.js, chess/src/Components/Networking.js
Deployment in front end may require change in credentials
=> Changed credentials to true

chess/src/App.js, chess/src/Components/ChessMLAlgorithm.js, chess/src/Components/ChooseDifficulty.js, chess/src/Components/HomePage.js, chess/src/Components/PlayAI.js, chess/src/Components/PlayOnline.js
added two levels of difficulty. added hints option for users
=> Difficulty

chess/src/Components/Networking.js
Added networking post request for leaderboard.
=> Added networking post request for leaderboard

chess/src/Components/Leaderboard.js, chess/src/Components/Networking.js, chess/src/Components/PlayOnline.js
Added win/lose logic to playOnline to automatically update the leaderboard
=> Leaderboard

chess/package-lock.json, chess/package.json, chess/src/Components/PlayOnline.js, chess/src/Components/Theme.js, chess/yarn.lock
added a loading component when only one player is in the room. added constraints on when a player can move their piece and stopped players from moving their opponents pieces. Added function for when there is a draw.
=> added loading and player turn constraints

chess/src/Components/GetCookies.js, chess/src/Components/Networking.js
attempted to add sameSite = None to cookies
=> Final deployment

chess/src/Components/Networking.js
cookies are only set if log in credentials are valid and clears cookies when logging out
=> finished setting up frontend cookies

chess/package-lock.json, chess/package.json, chess/src/App.js, chess/src/Components/CreateAccount.js, chess/src/Components/CreateAccount.test.js, chess/src/Components/Header.js, chess/src/Components/HomePage.js, chess/src/Components/Leaderboard.js, chess/src/Components/LogIn.js, chess/src/Components/LogIn.test.js, chess/src/Components/Login.css, chess/src/Components/header.css, chess/src/Components/home.css, chess/src/Testing/App.test.js, chess/yarn.lock
Added CSS to Login and Create Account pages.
Written basic tests for inputs and buttons.
=> written tests and added styling

chess/src/Components/ChooseDifficulty.js, chess/src/Components/PlayAI.js, chess/src/Components/SavedGame.js
Foxed the big on the easy setting, also made medium  hard and extra hard a bit less hard. passed the difficulties as strings and then changes into integers before using them in the algorithm.
=> fixed the play ai bug

chess/src/App.js, chess/src/Components/CreateAccount.test.js, chess/src/Components/Header.js, chess/src/Components/HomePage.js, chess/src/Components/Leaderboard.js, chess/src/Components/LogIn.js, chess/src/Components/LogIn.test.js, chess/src/Components/header.css, chess/src/Components/home.css, chess/src/Components/leaderboard.css
Added CSS for buttons in the home page and changed the leaderboard table styling.
Initial draft for README added. 
Tests for rending of buttons and redirects.
=> tests written and front end read me

chess/src/Components/ChooseDifficulty.js, chess/src/Components/Networking.js, chess/src/Components/PlayAI.js, chess/src/Components/SavedGame.css, chess/src/Components/SavedGame.js
added css to the saved game component and added to the networking function to account for the new column in the db
=> saved users colour and added saved game css

README.md
Initial draft.
Still need to add screenshots of the website to show website flow.
=> read me for front end draft

chess/src/Components/ChooseDifficulty.js, chess/src/Components/Networking.js, chess/src/Components/PlayAI.js, chess/src/Components/SavedGame.js
fixed the problem we were having with playing after a game has been saved.
=> fixed the play issue with saved games and colours

chess/src/Components/ChooseDifficulty.js, chess/src/Components/Login.css, chess/src/Components/Networking.js, chess/src/Components/PlayAI.js
added css to difficulty options
=> Savegame hotfix

chess/src/Components/PlayAI.js, chess/src/Components/SavedGame.js
updates orientation for saved games and games
=> orientation fix

chess/src/Components/PlayAI.js
fixed the stalemate message and added message for check
=> added check messages

chess/src/Components/PlayAI.js, chess/src/Components/play.css
I fixed the buttons so they they disable properly when the user doesnt want hints. (i noticed that the same ternary operator was being used for all the hint settings)
=> adisabled hint buttons correctly

chess/src/Components/GameCard.js, chess/src/Components/PlayAI.js, chess/src/Components/PlayOnline.js, chess/src/Components/__test__/ChooseDifficulty.test.js, chess/src/Components/__test__/PlayAI.test.js, chess/src/Components/__test__/__snapshots__/PlayAI.test.js.snap, chess/src/Testing/App.test.js
fixed "the winner is w message" and added some tests
=> tests for buttons on playai and changed name of playvsrandom to playai

chess/src/App.js, chess/src/Components/ChooseRoom.js, chess/src/Components/PlayAI.js, chess/src/Components/__test__/PlayAI.test.js
tests added for 'in check" message appearing when the user has asked for in check hints, test for hint buttons enabled when all hints have been chosen on difficulty options page
=> added tests for play ai

chess/src/App.js, chess/src/Components/PlayAI.js, chess/src/Components/__test__/PlayAI.test.js
Reverts ErikBoonprakong/chess-frontend#85
=> Revert "added tests for play ai"

chess/src/Components/ChooseRoom.js, chess/src/Components/PlayOnline.js
Reverts ErikBoonprakong/chess-frontend#92
=> Revert "board reset hotfix"

chess/src/Components/ChooseDifficulty.js, chess/src/Components/ChooseRoom.js, chess/src/Components/GameCard.js, chess/src/Components/Header.js, chess/src/Components/Leaderboard.js, chess/src/Components/PlayAI.js, chess/src/Components/SavedGames.js
took out commented out code and console logs
=> took out console logs and added some comments

chess/src/Components/ChooseRoom.css, chess/src/Components/ChooseRoom.js, chess/src/Components/PlayAI.js, chess/src/Components/PlayOnline.js
Added a Link Button to PlayOnline so players can leave a room if there are already 2 players.
=> leave a room

chess/src/Components/PlayOnline.js, chess/src/Components/__test__/PlayAI.test.js, chess/src/Components/__test__/PlayOnline.test.js
=> added play online test

chess/src/Components/play.css
=> added leave room button css

chess/src/Components/GameCard.js
fixed the time shown on saved games. doesnt show midnight for every game now. just shows date
=> changed last played to just show date
